global class ContactDocumentEmailHandler implements Messaging.InboundEmailHandler{
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope env)
    {   
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        String conid = email.subject;
        if(conid.contains(':')){
                conid =email.subject.Split(': ')[1];
            }
            if(conid!=null){
                List<TR1__ContactDocument__c> condoc = [Select Id,Name, TR1__isDefault__c  from TR1__ContactDocument__c where TR1__Contact__c =:conid  order by createddate DESC limit 1];
                update condoc;
            }
        return result;
    }    
    

}